In [4]:
import pandas as pd 
df = pd.read_csv("Popular_Baby_Names.csv")
df.head()

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,SOPHIA,119,1
1,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,CHLOE,106,2
2,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,EMILY,93,3
3,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,OLIVIA,89,4
4,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,EMMA,75,5

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11345 entries, 0 to 11344
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year of Birth       11345 non-null  int64
 1   Gender              11345 non-null  str
 2   Ethnicity           11345 non-null  str
 3   Child's First Name  11345 non-null  str
 4   Count               11345 non-null  int64
 5   Rank                11345 non-null  int64
dtypes: int64(3), str(3)
memory usage: 531.9 KB

In [6]:
df.isnull().sum()

Year of Birth         0
Gender                0
Ethnicity             0
Child's First Name    0
Count                 0
Rank                  0
dtype: int64

In [ ]:
df.describe() #un tableau statistiques pr les valeurs numeriques

       Year of Birth         Count          Rank
count   11345.000000  11345.000000  11345.000000
mean     2013.552578     32.836844     57.656765
std         1.746367     36.981866     25.186882
min      2011.000000     10.000000      1.000000
25%      2012.000000     13.000000     38.000000
50%      2014.000000     20.000000     59.000000
75%      2015.000000     35.000000     79.000000
max      2016.000000    387.000000    102.000000

In [ ]:
df.describe().T #transposè

,count,mean,std,min,25%,50%,75%,max
Year of Birth,11345.0,2013.552578,1.746367,2011.0,2012.0,2014.0,2015.0,2016.0
Count,11345.0,32.836844,36.981866,10.0,13.0,20.0,35.0,387.0
Rank,11345.0,57.656765,25.186882,1.0,38.0,59.0,79.0,102.0

In [ ]:
import numpy as np
df.describe(exclude = np.number).T # resume categorique  
#  unique = il n'y a que 2 valeurs distinctes dans cette colonne (probablement "MALE" et "FEMALE").

                    count unique                 top  freq
Gender              11345      2              FEMALE  5806
Ethnicity           11345      7  WHITE NON HISPANIC  3365
Child's First Name  11345   3016               Avery    24

In [ ]:
df["Name lenght"] = df['Child\'s First Name'].apply(len)# on a creer une nvlle colonne Name lengh et 3amernaha b len ta3 chq nom 
df.head()

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank,Name lenght
0,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,SOPHIA,119,1,6
1,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,CHLOE,106,2,5
2,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,EMILY,93,3,5
3,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,OLIVIA,89,4,6
4,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,EMMA,75,5,4

In [12]:
df.sort_values(by = 'Name lenght',ascending = False)

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank,Name lenght
10300,2016,MALE,WHITE NON HISPANIC,Christopher,71,46,11
1163,2011,MALE,BLACK NON HISPANIC,CHRISTOPHER,80,19,11
1665,2011,MALE,WHITE NON HISPANIC,CHRISTOPHER,92,36,11
3396,2012,MALE,HISPANIC,MAXIMILIANO,17,93,11
6491,2014,MALE,ASIAN AND PACIFIC ISLANDER,Christopher,18,50,11
...,...,...,...,...,...,...,...
10910,2016,FEMALE,WHITE NON HISPANIC,Gia,13,81,3
10904,2016,FEMALE,WHITE NON HISPANIC,Amy,13,81,3
116,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,YU,13,35,2
10015,2016,MALE,ASIAN AND PACIFIC ISLANDER,Md,14,55,2
4799,2013,MALE,ASIAN AND PACIFIC ISLANDER,Md,11,56,2

In [13]:
df['Child\'s First Name']= df['Child\'s First Name'].apply(str.lower)# on a applique minuscule
df

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank,Name lenght
0,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,sophia,119,1,6
1,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,chloe,106,2,5
2,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,emily,93,3,5
3,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,olivia,89,4,6
4,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,emma,75,5,4
...,...,...,...,...,...,...,...
11340,2016,FEMALE,BLACK NON HISPANIC,saniyah,10,43,7
11341,2016,FEMALE,BLACK NON HISPANIC,skye,10,43,4
11342,2016,FEMALE,BLACK NON HISPANIC,tiana,10,43,5
11343,2016,FEMALE,BLACK NON HISPANIC,violet,10,43,6
11344,2016,FEMALE,BLACK NON HISPANIC,zahra,10,43,5

In [14]:
df.describe(exclude=np.number).T

                    count unique                 top  freq
Gender              11345      2              FEMALE  5806
Ethnicity           11345      7  WHITE NON HISPANIC  3365
Child's First Name  11345   1775               avery    33

In [ ]:
df.duplicated().sum() # sum des dupliqués

np.int64(0)

In [17]:
df.drop_duplicates(inplace=True) #enleve les dup m la data originale pas la copie

In [20]:
df[(df["Gender"]== "MALE") & (df["Year of Birth"]>=2015)]

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank,Name lenght
7237,2015,MALE,HISPANIC,liam,356,1,4
7238,2015,MALE,HISPANIC,dylan,339,2,5
7239,2015,MALE,HISPANIC,ethan,332,3,5
7240,2015,MALE,HISPANIC,matthew,308,4,7
7241,2015,MALE,HISPANIC,noah,297,5,4
...,...,...,...,...,...,...,...
11166,2016,MALE,BLACK NON HISPANIC,myles,10,57,5
11167,2016,MALE,BLACK NON HISPANIC,omar,10,57,4
11168,2016,MALE,BLACK NON HISPANIC,oumar,10,57,5
11169,2016,MALE,BLACK NON HISPANIC,wyatt,10,57,5
11170,2016,MALE,BLACK NON HISPANIC,zayden,10,57,6

In [21]:
df.to_csv("cleaned_baby_data.csv", index= False)

In [22]:
import pandas as pd
import numpy as np

# Creating a DataFrame with missing values
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, 5],
    'D': [1, 2, 3, 4, 5]
}

df = pd.DataFrame(data)
df

     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  2.0  2
2  NaN  3.0  3.0  3
3  4.0  4.0  NaN  4
4  5.0  5.0  5.0  5

In [23]:
df.isnull().sum()

A    1
B    1
C    1
D    0
dtype: int64

In [ ]:
df.dropna() #supprimer les lignes (ou colonnes) contenant des valeurs manquantes (les NaN, "Not a Number") dans ton DataFrame.(une seule missing)

     A    B    C  D
1  2.0  2.0  2.0  2
4  5.0  5.0  5.0  5

In [25]:
df.dropna(how = 'all')# lzm ga3 la ligne wla colonne nan pr qu il la supprime

     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  2.0  2
2  NaN  3.0  3.0  3
3  4.0  4.0  NaN  4
4  5.0  5.0  5.0  5

In [26]:
dropping_rows = df.dropna()# how ='any' if how ='all'deletes onmy if 
dropping_rows

     A    B    C  D
1  2.0  2.0  2.0  2
4  5.0  5.0  5.0  5

In [27]:
dropping_columns = df.dropna(axis=1)
dropping_columns

   D
0  1
1  2
2  3
3  4
4  5

In [29]:
df.fillna({
    'A':df['A'].mean(),
    'B':df['B'].median(),
    'C':df['C'].mode()[0]
})

     A    B    C  D
0  1.0  3.5  1.0  1
1  2.0  2.0  2.0  2
2  3.0  3.0  3.0  3
3  4.0  4.0  1.0  4
4  5.0  5.0  5.0  5

In [36]:
import pandas as pd
import numpy as np
from scipy import stats

# Create a DataFrame with sample data
df = pd.DataFrame({'Height': [170, 160, 130, 190, 180, 150, 140, 200, 175, 165,500]})

# Calculate the z-score of each data point
z_scores = np.abs(stats.zscore(df['Height']))
threshold = 3
outliers = df[z_scores > threshold]

print("Outliers based on z-score:")
print(outliers)

Outliers based on z-score:
    Height
10     500

In [37]:
# Calculate Q1, Q3, and IQR
Q1 = df['Height'].quantile(0.25)
Q3 = df['Height'].quantile(0.75)
IQR = Q3 - Q1

# Define threshold and detect outliers
threshold = 1.5
outliers = df[(df['Height'] < (Q1 - threshold * IQR)) | (df['Height'] > (Q3 + threshold * IQR))]

print("Outliers based on IQR:")
outliers

Outliers based on IQR:

    Height
10     500

In [38]:
df_clean = df.drop(outliers.index)
df_clean

   Height
0     170
1     160
2     130
3     190
4     180
5     150
6     140
7     200
8     175
9     165

In [39]:
outliers.index

RangeIndex(start=10, stop=11, step=1)

In [40]:
# Replace outliers with the median value of the dataset
median_value = df['Height'].median()
df.loc[df.index.isin(outliers.index), 'Height'] = median_value
df

    Height
0      170
1      160
2      130
3      190
4      180
5      150
6      140
7      200
8      175
9      165
10     170

In [41]:
import pandas as pd
# Create a sample dataframe
df = pd.DataFrame({'Priority': ['Low', 'Medium', 'High', 'Medium', 'Low']})
df

  Priority
0      Low
1   Medium
2     High
3   Medium
4      Low

In [42]:
# Define a mapping dictionary
priority_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
# Use the replace function to apply the dictionary mapping
df['Priority_Encoded'] = df['Priority'].map(priority_mapping)
# Display the updated dataframe
df

  Priority  Priority_Encoded
0      Low                 1
1   Medium                 2
2     High                 3
3   Medium                 2
4      Low                 1

In [43]:
import pandas as pd
# Create a sample dataframe with a categorical variable
df = pd.DataFrame({'Fruit': ['Apple', 'Orange', 'Banana', 'Banana', 'Orange', 'Apple']})
df

    Fruit
0   Apple
1  Orange
2  Banana
3  Banana
4  Orange
5   Apple

In [44]:
# Perform one-hot encoding
one_hot_df = pd.get_dummies(df, columns=['Fruit'], dtype=int)
# Display the encoded dataframe
one_hot_df

   Fruit_Apple  Fruit_Banana  Fruit_Orange
0            1             0             0
1            0             0             1
2            0             1             0
3            0             1             0
4            0             0             1
5            1             0             0

In [45]:
from sklearn.preprocessing import LabelEncoder
# Sample data
data = ['apple', 'banana', 'banana', 'orange', 'kiwi', 'mango', 'apple']
# Create label encoder object
le = LabelEncoder()

# Fit and transform the data
encoded_data = le.fit_transform(data)

# Display the encoded data
print(encoded_data)

[0 1 1 4 2 3 0]